config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/home'

  resources :attractionsdbs
  resources :users

  get '/home'=>'attrctionsdbs#home'
end

app/models/attractionsdb.rb
class Attractionsdb < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attractionsdbs_controller.rb
class AttractionsdbsController < ApplicationController
  before_action :set_attractionsdb, only: [:show, :edit, :update, :destroy]

  # GET /attractionsdbs
  # GET /attractionsdbs.json
  def index
    @attractionsdbs = Attractionsdb.all
  end

  # GET /attractionsdbs/1
  # GET /attractionsdbs/1.json
  def show
  end

  # GET /attractionsdbs/new
  def new
    @attractionsdb = Attractionsdb.new
  end

  # GET /attractionsdbs/1/edit
  def edit
  end

  # POST /attractionsdbs
  # POST /attractionsdbs.json
  def create
    @attractionsdb = Attractionsdb.new(attractionsdb_params)

    respond_to do |format|
      if @attractionsdb.save
        format.html { redirect_to @attractionsdb, notice: 'Attractionsdb was successfully created.' }
        format.json { render :show, status: :created, location: @attractionsdb }
      else
        format.html { render :new }
        format.json { render json: @attractionsdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractionsdbs/1
  # PATCH/PUT /attractionsdbs/1.json
  def update
    respond_to do |format|
      if @attractionsdb.update(attractionsdb_params)
        format.html { redirect_to @attractionsdb, notice: 'Attractionsdb was successfully updated.' }
        format.json { render :show, status: :ok, location: @attractionsdb }
      else
        format.html { render :edit }
        format.json { render json: @attractionsdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractionsdbs/1
  # DELETE /attractionsdbs/1.json
  def destroy
    @attractionsdb.destroy
    respond_to do |format|
      format.html { redirect_to attractionsdbs_url, notice: 'Attractionsdb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attractionsdb
      @attractionsdb = Attractionsdb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attractionsdb_params
      params.require(:attractionsdb).permit(:name, :description, :rating, :entry, :web)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Name, :Description, :Rating, :Entry, :Web)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractionsdbs_helper.rb
module AttractionsdbsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attractionsdbs/_form.html.erb
<%= form_for(@attractionsdb) do |f| %>
  <% if @attractionsdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attractionsdb.errors.count, "error") %> prohibited this attractionsdb from being saved:</h2>

      <ul>
      <% @attractionsdb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_field :entry %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractionsdbs/edit.html.erb
<h1>Editing Attractionsdb</h1>

<%= render 'form' %>

<%= link_to 'Show', @attractionsdb %> |
<%= link_to 'Back', attractionsdbs_path %>

app/views/attractionsdbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attractionsdbs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Entry</th>
      <th>Web</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractionsdbs.each do |attractionsdb| %>
      <tr>
        <td><%= attractionsdb.name %></td>
        <td><%= attractionsdb.description %></td>
        <td><%= attractionsdb.rating %></td>
        <td><%= attractionsdb.entry %></td>
        <td><%= attractionsdb.web %></td>
        <td><%= link_to 'Show', attractionsdb %></td>
        <td><%= link_to 'Edit', edit_attractionsdb_path(attractionsdb) %></td>
        <td><%= link_to 'Destroy', attractionsdb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attractionsdb', new_attractionsdb_path %>

app/views/attractionsdbs/new.html.erb
<h1>New Attractionsdb</h1>

<%= render 'form' %>

<%= link_to 'Back', attractionsdbs_path %>

app/views/attractionsdbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attractionsdb.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attractionsdb.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @attractionsdb.rating %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @attractionsdb.entry %>
</p>

<p>
  <strong>Web:</strong>
  <%= @attractionsdb.web %>
</p>

<%= link_to 'Edit', edit_attractionsdb_path(@attractionsdb) %> |
<%= link_to 'Back', attractionsdbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MurrayAttractions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<body background="#4682B4">
    <h1 align="center">Welcome to Murray Attractions website!!</h1>
    <table border="5" cellpadding="10px" cellspacing="10px" align="center">
        
        <tr>
            
            <td><a href="https://touristattractions-revanththirunagari.c9.io/static_pages/home">Home Page</a></td>
            <td><a href="https://touristattractions-revanththirunagari.c9.io/attractionsdbs/1/edit">Edit a attraction </a></td>
            <td><a href="https://touristattractions-revanththirunagari.c9.io/attractionsdbs">All attractions</a></td>
            <td><a href="https://touristattractions-revanththirunagari.c9.io/attractionsdbs/1/edit">Delete a attraction</a></td>
            <td><a href="#">Search</a></td>
            
            
            
            
            
            
        </tr>
        
        
        
        
        
        
    </table>
    
    
    
    
    
</body>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field :Description %>
  </div>
  <div class="field">
    <%= f.label :Rating %><br>
    <%= f.text_field :Rating %>
  </div>
  <div class="field">
    <%= f.label :Entry %><br>
    <%= f.text_field :Entry %>
  </div>
  <div class="field">
    <%= f.label :Web %><br>
    <%= f.text_field :Web %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Entry</th>
      <th>Web</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Name %></td>
        <td><%= user.Description %></td>
        <td><%= user.Rating %></td>
        <td><%= user.Entry %></td>
        <td><%= user.Web %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.Name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.Description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @user.Rating %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @user.Entry %>
</p>

<p>
  <strong>Web:</strong>
  <%= @user.Web %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>